language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t ronargame/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ronargame/docker-react npm run test
